spring:
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true