version: '3.8'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/library

